#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER ${NEWSLETTER_ENGINE_DB_USER} WITH PASSWORD '${NEWSLETTER_ENGINE_DB_PASSWORD}';
  CREATE USER ${HERMES_DB_USER} WITH PASSWORD '${HERMES_DB_PASSWORD}';

  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${NEWSLETTER_ENGINE_DB_USER};
  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${HERMES_DB_USER};

  GRANT USAGE, CREATE ON SCHEMA public TO ${NEWSLETTER_ENGINE_DB_USER};
  GRANT USAGE ON SCHEMA public TO ${HERMES_DB_USER};

  -- Future tables created by the superuser will be accessible to both roles
  ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA public
    GRANT ALL ON TABLES TO ${NEWSLETTER_ENGINE_DB_USER};
  ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO ${NEWSLETTER_ENGINE_DB_USER};
  ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA public
    GRANT SELECT ON TABLES TO ${HERMES_DB_USER};
EOSQL
