#!/bin/bash
set -e

# Create users (must happen in an existing DB context before CREATE DATABASE)
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER ${NEWSLETTER_ENGINE_DB_USER} WITH PASSWORD '${NEWSLETTER_ENGINE_DB_PASSWORD}';
  CREATE USER ${HERMES_DB_USER} WITH PASSWORD '${HERMES_DB_PASSWORD}';
  CREATE USER ${LITELLM_DB_USER} WITH PASSWORD '${LITELLM_DB_PASSWORD}';

  -- Restrict hermes_db access: revoke PUBLIC default, grant only to legitimate roles
  REVOKE CONNECT ON DATABASE ${POSTGRES_DB} FROM PUBLIC;
  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${NEWSLETTER_ENGINE_DB_USER};
  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${HERMES_DB_USER};

  GRANT USAGE, CREATE ON SCHEMA public TO ${NEWSLETTER_ENGINE_DB_USER};
  GRANT USAGE ON SCHEMA public TO ${HERMES_DB_USER};

  -- Future tables created by the superuser will be accessible to both roles
  ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA public
    GRANT ALL ON TABLES TO ${NEWSLETTER_ENGINE_DB_USER};
  ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO ${NEWSLETTER_ENGINE_DB_USER};
  ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA public
    GRANT SELECT ON TABLES TO ${HERMES_DB_USER};

  -- Alembic runs as newsletter_engine, so Hermes needs read access to those objects too.
  ALTER DEFAULT PRIVILEGES FOR ROLE ${NEWSLETTER_ENGINE_DB_USER} IN SCHEMA public
    GRANT SELECT ON TABLES TO ${HERMES_DB_USER};
  ALTER DEFAULT PRIVILEGES FOR ROLE ${NEWSLETTER_ENGINE_DB_USER} IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO ${HERMES_DB_USER};
EOSQL

# CREATE DATABASE cannot run inside a transaction block — separate psql call
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE ${LITELLM_DB_NAME} OWNER ${LITELLM_DB_USER};
EOSQL
